### ISSUE TITLE
Cannot clone neorv32-setups repository

### ISSUE THREAD

**Issue by tmeissner** [stnolting/neorv32-setups#68] opened 2022-12-15 13:48 UTC
I assume the error comes from Github renaming the master branch  to main ...
As I'm not very familiar with git submodules maybe some one can help here or fix this?

```
$ git clone --recurse-submodules --remote-submodules https://github.com/stnolting/neorv32-setups.git
Cloning into 'neorv32-setups'...
remote: Enumerating objects: 632, done.
remote: Counting objects: 100% (293/293), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 632 (delta 138), reused 197 (delta 102), pack-reused 339
Receiving objects: 100% (632/632), 332.16 KiB | 1.81 MiB/s, done.
Resolving deltas: 100% (305/305), done.
Submodule 'constraints' (https://github.com/hdl/constraints) registered for path 'constraints'
Submodule 'neorv32' (https://github.com/stnolting/neorv32) registered for path 'neorv32'
Cloning into '/home/torsten/Projects/github.com/neorv32-setups/constraints'...
remote: Enumerating objects: 1471, done.        
remote: Counting objects: 100% (112/112), done.        
remote: Compressing objects: 100% (45/45), done.        
remote: Total 1471 (delta 72), reused 84 (delta 63), pack-reused 1359        
Receiving objects: 100% (1471/1471), 3.11 MiB | 5.91 MiB/s, done.
Resolving deltas: 100% (699/699), done.
Cloning into '/home/torsten/Projects/github.com/neorv32-setups/neorv32'...
remote: Enumerating objects: 26299, done.        
remote: Counting objects: 100% (854/854), done.        
remote: Compressing objects: 100% (397/397), done.        
remote: Total 26299 (delta 565), reused 714 (delta 456), pack-reused 25445        
Receiving objects: 100% (26299/26299), 186.23 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (18045/18045), done.
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'constraints'
```

**Comment by stnolting** [comment] 2022-12-15 17:48
Hmm, I get the same error message... Maybe a problem with the `constraints` submodule/repository?! Anyway, this is my workaround (not git expert):

```bash
git clone https://github.com/stnolting/neorv32-setups.git
cd neorv32-setups/
git submodule update --init --recursive
```

**Comment by tmeissner** [comment] 2022-12-16 10:30
Mhm, This helps to get the neorv repo right, but the contraints repo is still not:

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   constraints (modified content)
        modified:   neorv32 (new commits, modified content)

no changes added to commit (use "git add" and/or "git commit -a")
$ git submodule update --init --recursive
Submodule path 'neorv32': checked out '0c27b24d64fcad0ec38a98f25e03de3b1c9ab71d'
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   constraints (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
$ ls -a constraints/
.  ..  .git
$
```

**Comment by umarcor** [comment] 2022-12-16 11:14
The default branch of hdl/constraints was changed from `master` to `main`. I thought that GitHub would handle that transparently, but it seems it does not. Hence, I believe we just need to update the submodule ref in this repo. I will try to deal with it later today.

**Comment by umarcor** [comment] 2022-12-17 18:03
Hmm, unfortunately, I cannot reproduce:

```
git clone --recurse-submodules --remote-submodules https://github.com/stnolting/neorv32-setups.git
Cloning into 'neorv32-setups'...
remote: Enumerating objects: 635, done.
remote: Counting objects: 100% (296/296), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 635 (delta 140), reused 196 (delta 102), pack-reused 339
Receiving objects: 100% (635/635), 332.57 KiB | 4.75 MiB/s, done.
Resolving deltas: 100% (307/307), done.
Submodule 'constraints' (https://github.com/hdl/constraints) registered for path 'constraints'
Submodule 'neorv32' (https://github.com/stnolting/neorv32) registered for path 'neorv32'
Cloning into '/home/umarcor/dev/tmp/neorv32-setups/constraints'...
remote: Enumerating objects: 1471, done.        
remote: Counting objects: 100% (112/112), done.        
remote: Compressing objects: 100% (45/45), done.        
remote: Total 1471 (delta 72), reused 84 (delta 63), pack-reused 1359        
Receiving objects: 100% (1471/1471), 3.11 MiB | 15.70 MiB/s, done.
Resolving deltas: 100% (699/699), done.
Cloning into '/home/umarcor/dev/tmp/neorv32-setups/neorv32'...
remote: Enumerating objects: 26375, done.        
remote: Counting objects: 100% (930/930), done.        
remote: Compressing objects: 100% (371/371), done.        
remote: Total 26375 (delta 629), reused 822 (delta 558), pack-reused 25445        
Receiving objects: 100% (26375/26375), 185.21 MiB | 22.74 MiB/s, done.
Resolving deltas: 100% (18115/18115), done.
Submodule path 'constraints': checked out '34edf541e5e5755309d7cb02bd0b8329175f7c1e'
Submodule path 'neorv32': checked out '9c2af7ea1d822f55f3b3db14e6d1c30e10f31981'
```

I'm using `git version 2.30.2`.

I reviewed how is the submodule setup in this repo, and it seems to point to a specific commit hash, not to a branch name. Maybe you are using a more recent version of git and the behaviour changed?

**Comment by stnolting** [comment] 2022-12-17 20:11
I think this is just some version issue. Using `git version 2.25.1` (on WSL/Ubuntu) I get the same error as @tmeissner, but with `git version 2.29.2.windows.3` (on Windows) everything just works fine.

**Comment by stnolting** [comment] 2023-01-25 18:37
@tmeissner can we close this?

**Comment by tmeissner** [comment] 2023-01-25 19:04
Yes, this can be closed.

**Closed** 2023-01-25 19:07 UTC
